name: cip
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.1
  dio: ^4.0.6
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  retrofit: ^3.0.1+1
  syncfusion_flutter_charts: ^20.1.58+1
  syncfusion_flutter_core: ^20.1.58+1
  syncfusion_flutter_gauges: ^20.1.58
  shared_preferences: ^2.0.15
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  very_good_analysis: ^3.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.1
  retrofit_generator: ^4.0.1 
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
