name: cip
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.1
  dio: ^4.0.6
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  retrofit: ^3.0.1+1
  syncfusion_flutter_charts: ^20.1.59
  syncfusion_flutter_core: ^20.1.59
  syncfusion_flutter_gauges: ^20.1.59
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0
  mqtt_client: ^9.6.8
  signalr_netcore: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.21.1

  flutter_lints: ^2.0.1
  very_good_analysis: ^3.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.1
  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter_gen:
  line_length: 120
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
